"""hallo

Revision ID: 501a9f48d965
Revises: d4f212ae9d9d
Create Date: 2022-06-14 17:55:35.831596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501a9f48d965'
down_revision = 'd4f212ae9d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('password2', sa.String(length=80), nullable=False),
    sa.Column('password22', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
