"""rm pw

Revision ID: 658aa22260a6
Revises: 0891a0762cd5
Create Date: 2022-06-14 21:40:38.543083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658aa22260a6'
down_revision = '0891a0762cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password2')
        batch_op.drop_column('password423')
        batch_op.drop_column('password223')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password223', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('password423', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('password2', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
