"""Audiobook Column

Revision ID: e249df4da37a
Revises: 658aa22260a6
Create Date: 2022-06-14 22:13:32.083523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e249df4da37a'
down_revision = '658aa22260a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('playcount', sa.Integer(), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audiobook')
    # ### end Alembic commands ###
